// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Capacitor } from '@capacitor/core';
import { Preferences } from '@capacitor/preferences';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const supabaseKeyForClient = (SUPABASE_ANON_KEY ?? SUPABASE_PUBLISHABLE_KEY) as string | undefined;

if (!SUPABASE_URL || !supabaseKeyForClient) {
  // eslint-disable-next-line no-console
  console.error('[app] Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY/VITE_SUPABASE_PUBLISHABLE_KEY');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isNative = Capacitor.isNativePlatform();

// On native (Capacitor), localStorage may not persist reliably across app kills/background.
// Preferences uses native storage, which is much more stable for auth sessions.
const capacitorStorage = {
  async getItem(key: string) {
    const { value } = await Preferences.get({ key });
    return value ?? null;
  },
  async setItem(key: string, value: string) {
    await Preferences.set({ key, value });
  },
  async removeItem(key: string) {
    await Preferences.remove({ key });
  },
};

const storage: any = isNative ? capacitorStorage : localStorage;

export const supabase = createClient<Database>(SUPABASE_URL ?? '', supabaseKeyForClient ?? '', {
  auth: {
    storage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: !isNative,
  }
});